In [1]:
import pandas as pd

combined_raw_data = pd.read_csv('../data/raw/combined_raw_data.csv')
combined_raw_data.head()

,Unnamed: 0,AAPL,AAPL.1,AAPL.2,AAPL.3,AAPL.4,ABBV,ABBV.1,ABBV.2,ABBV.3,...,WFC,WFC.1,WFC.2,WFC.3,WFC.4,XOM,XOM.1,XOM.2,XOM.3,XOM.4
0,NaN,Open,High,Low,Close,Volume,Open,High,Low,Close,...,Open,High,Low,Close,Volume,Open,High,Low,Close,Volume
1,2013-01-02 00:00:00-05:00,16.726068314487094,16.76170582486638,16.357915654650395,16.581403732299805,560518000,20.443969182924974,20.724987921510643,19.963899040598832,20.561059951782227,...,24.054133516614662,24.081601041490806,23.855000509881002,24.067867279052734,30443000,51.1564171751512,51.698340891843806,50.83592298139442,51.69251251220703,16143700
2,2013-01-03 00:00:00-05:00,16.54666598301802,16.600726265962198,16.338881397575303,16.372102737426758,352965200,20.490810665292805,20.490810665292805,19.999031119992935,20.391284942626953,...,24.01979354714219,24.060994822666938,23.765725563356078,23.868724822998047,25374800,51.54683097433153,51.797397934304485,51.372019607728795,51.59927749633789,13268200
3,2013-01-04 00:00:00-05:00,16.217164068387454,16.26729848146638,15.880721720706754,15.916057586669922,594333600,20.26834354533764,20.426415821599683,20.05172697415856,20.133689880371094,...,23.751992504096986,24.06099553101302,23.655858811155703,23.992326736450195,31420300,51.57014431185151,51.913943139969966,51.49439315796553,51.838191986083984,11427900
4,2013-01-07 00:00:00-05:00,15.765068649115538,15.985537407314801,15.5597000709912,15.8224515914917,484156400,19.993178739921877,20.754265590492512,19.993178739921877,20.174667358398438,...,23.971730706291257,24.01293198869821,23.66959582698138,23.87559700012207,28135100,51.459432326267645,51.564320943400205,51.02822554283449,51.23800277709961,11799800

In [2]:
combined_raw_data.tail(10)

,Unnamed: 0,AAPL,AAPL.1,AAPL.2,AAPL.3,AAPL.4,ABBV,ABBV.1,ABBV.2,ABBV.3,...,WFC,WFC.1,WFC.2,WFC.3,WFC.4,XOM,XOM.1,XOM.2,XOM.3,XOM.4
3300,2026-02-13 00:00:00-05:00,261.7688319830923,261.9886306947134,255.21485759663088,255.5445556640625,56290700,226.54058542130937,232.8085924722355,226.12404294765793,229.59524536132812,...,85.19293697552165,86.95287175519661,84.60628699161407,86.48554992675781,12425000,149.53503667709694,150.63755397112487,146.9823556296224,147.44918823242188,20166000
3301,2026-02-17 00:00:00-05:00,257.8124646511843,266.0449008431299,255.30478047881587,263.6371154785156,58469100,230.74570987781337,233.31439609014336,229.28780362038455,230.94406127929688,...,87.33071598433709,88.33496899109318,86.81366777208405,86.90316009521484,12361900,147.20088103709168,148.12461916232286,144.1714401084163,145.20443725585938,19766600
3302,2026-02-18 00:00:00-05:00,263.35737977838915,266.57441720150126,262.20844437502524,264.106689453125,34203300,232.0746750669173,232.0746750669173,224.20992945360547,226.83811950683594,...,87.32077310146762,88.89179316374123,87.15174131383698,88.05656433105469,8250900,147.1512117547303,149.96213457527915,146.61485893888485,149.66415405273438,19849700
3303,2026-02-19 00:00:00-05:00,262.35827847824623,264.2365527856389,259.81060750150084,260.3401184082031,30845300,227.08605630267382,227.48275908475674,221.18501540305448,222.5040740966797,...,87.34065112054601,87.65883929479293,86.10770228943365,87.07218933105469,10427300,151.17391296007145,152.34596565632472,149.82308104142925,149.95220947265625,20305000
3304,2026-02-20 00:00:00-05:00,258.73163460792017,264.5063132392292,257.9223826043077,264.3364562988281,42070500,223.18838471570882,224.82481774591858,221.27427184389998,222.9602813720703,...,86.86338379534273,88.20570791120146,85.65031793540311,88.19576263427734,14255000,149.47544461771784,149.79327938752533,145.47261494560635,146.28707885742188,25908600
3305,2026-02-23 00:00:00-05:00,263.24744081710827,269.1819753311392,263.13755670993424,265.9349670410156,37308200,223.96198351522077,229.52581048394183,223.93221642955518,227.59185791015625,...,87.66878364517419,88.09633955426678,83.30373981296177,84.66595458984375,20607000,147.15121695350626,150.2501932791706,147.13136269897575,149.74362182617188,16073100
3306,2026-02-24 00:00:00-05:00,267.61343657617186,274.6369951599546,267.46358073991865,271.8895263671875,47014600,227.11581476882975,228.86132824659705,225.79675603737115,226.5604248046875,...,83.92021686875192,84.70572690381086,82.00118794412036,84.08924865722656,18817700,149.40590636909334,149.7038868797102,147.0320197225123,148.25372314453125,14185500
3307,2026-02-25 00:00:00-05:00,271.5298429675081,274.6869380517792,270.8005039088116,273.97760009765625,33714300,227.81998549119191,230.63661474365287,224.61655057527955,225.0529327392578,...,84.70572516622696,86.42588643440466,84.48697458044161,86.26679992675781,16620700,148.89935987129022,149.16752870809867,146.33675156146265,148.05508422851562,15225700
3308,2026-02-26 00:00:00-05:00,274.6969199809464,275.8558253670768,270.55071567552415,272.6987609863281,32345100,225.71741114521754,225.90585026765513,219.31057178178764,222.84127807617188,...,86.39606013971662,87.81793139341235,85.09350945896901,85.80941772460938,18768400,146.8134999377823,149.94227252800187,145.78051802335915,147.53857421875,15632100
3309,2026-02-27 00:00:00-05:00,272.5588900215503,272.5588900215503,262.6480379442022,263.93682861328125,72366500,223.2479061584604,230.3589103120584,223.20822679977505,230.17047119140625,...,84.18867304292914,84.3378218523216,79.99266134228353,80.98697662353516,29145000,149.98200583536115,152.61413431248826,148.24380378097783,151.47189331054688,30275100

In [ ]:
combined_raw_data.info()

In [ ]:
APPL = pd.read_csv('../data/raw/by_ticker/AAPL.csv')
APPL.head()

,Date,Open,High,Low,Close,Volume
0,2010-03-01 00:00:00-05:00,6.159214,6.271472,6.150234,6.256206,550093600
1,2010-03-02 00:00:00-05:00,6.284344,6.311286,6.218785,6.252014,566546400
2,2010-03-03 00:00:00-05:00,6.254709,6.282549,6.224774,6.266383,372052800
3,2010-03-04 00:00:00-05:00,6.264886,6.313980,6.245428,6.307693,366041200
4,2010-03-05 00:00:00-05:00,6.434321,6.576814,6.425041,6.554362,899620400

In [4]:
period_0 = pd.read_csv('../data/processed/period_0_normalized.csv')
period_0.head(10)

,Unnamed: 0,AAPL,ABBV,AMD,AVGO,BAC,C,CMCSA,COP,CVX,...,MSFT,NFLX,NVDA,ORCL,PFE,SLB,TMUS,UNH,WFC,XOM
0,2013-01-03 05:00:00,-0.800705,-0.510449,-0.485160,0.149488,-0.376048,0.209089,-0.945146,-0.026320,-0.306868,...,-0.934323,1.433436,-0.032725,-0.819782,-0.242820,-0.450813,-0.420108,-3.564174,-0.778588,-0.159924
1,2013-01-04 05:00:00,-1.744336,-0.759073,1.190435,-0.385458,0.761204,1.576105,-0.092994,0.627651,0.378995,...,-1.284119,-0.278027,1.748975,0.615032,0.342015,0.985984,0.466867,0.060627,0.412863,0.389154
2,2013-01-07 05:00:00,-0.387719,0.070085,0.919171,-0.344759,-0.116072,0.053081,-0.407604,-0.605181,-0.489946,...,-0.182971,0.947876,-1.726286,-0.397743,0.032285,0.170904,-0.944180,-0.079231,-0.475151,-1.000909
3,2013-01-08 05:00:00,0.133411,-1.281487,-0.002382,-0.403334,-0.581404,-0.022065,0.493273,-0.745187,-0.321811,...,-0.402121,-0.728199,-1.323985,0.002709,0.100795,0.260537,-1.283691,-1.049747,-0.196606,0.527228
4,2013-01-09 05:00:00,-0.985794,0.271766,-0.459653,0.914688,-2.934080,-0.641153,0.489576,-0.103124,0.184412,...,0.302555,-0.484152,-1.352261,0.023906,1.491340,-0.290083,0.268995,1.281450,-0.043872,-0.334674
5,2013-01-10 05:00:00,0.718017,0.121390,-0.117789,0.893206,1.861094,1.180598,0.114468,0.249205,0.608702,...,-0.646030,0.591291,0.015184,0.925562,0.934503,0.932793,1.740684,0.941991,1.696769,0.920154
6,2013-01-11 05:00:00,-0.403004,0.372567,0.570296,1.019888,-0.809807,-0.741056,-0.133963,-0.207666,0.816441,...,0.836411,0.948564,-0.168994,-0.122667,-0.838956,0.434059,-1.049887,-0.477745,-0.796448,0.482194
7,2013-01-14 05:00:00,-2.233103,0.353009,-0.344687,0.216750,-0.874272,-0.188051,0.895594,0.201635,0.718067,...,0.082608,0.577064,-0.123003,0.190034,0.699728,-0.883966,-0.213508,0.661066,-0.879204,-0.034278
8,2013-01-15 05:00:00,-1.975479,0.790719,0.453170,-1.028989,0.418585,0.519605,0.519689,0.540919,0.375528,...,0.703394,-0.615392,-1.100489,-0.561509,-0.436991,-0.171991,0.315601,0.274518,0.816634,-0.053338
9,2013-01-16 05:00:00,2.438756,1.462991,0.446421,0.836183,1.212041,-0.142035,-0.091775,-0.130164,0.335669,...,-0.467321,-1.398379,0.437239,-0.144313,-0.069765,0.554176,-1.389172,-0.024927,-0.094278,-0.062976

In [5]:
period_0.tail(10)

,Unnamed: 0,AAPL,ABBV,AMD,AVGO,BAC,C,CMCSA,COP,CVX,...,MSFT,NFLX,NVDA,ORCL,PFE,SLB,TMUS,UNH,WFC,XOM
817,2016-04-04 04:00:00,0.590678,1.681822,-0.002382,-0.613549,-0.242933,-0.625860,-0.264763,-0.946848,-0.636300,...,-0.225070,-0.481206,-0.624172,-0.177655,1.957986,0.458991,0.328686,-0.320513,0.047359,0.200163
818,2016-04-05 04:00:00,-0.749498,-0.684114,-0.761118,-0.379083,-1.503098,-0.846714,-0.441035,-0.074124,-0.587624,...,-1.085320,0.095144,-0.155516,-0.981332,1.800754,0.007768,-0.720685,-1.469450,-1.867596,-0.987541
819,2016-04-06 04:00:00,0.602623,1.237730,0.433505,0.647649,0.362432,0.528625,1.330639,2.393435,1.666091,...,0.598698,-0.113268,0.001705,0.375493,4.315984,0.437638,-0.106164,0.485723,1.010752,1.130294
820,2016-04-07 04:00:00,-1.368085,-0.600898,-1.784875,-0.844936,-2.012150,-2.477359,-1.082053,-0.592025,-0.037740,...,-0.841162,-0.193763,-0.661268,-1.424525,-0.497425,-1.045062,-0.417275,-0.741661,-2.184634,-0.975419
821,2016-04-08 04:00:00,0.037352,-0.836825,1.123905,0.258526,0.131550,0.309032,0.207795,1.265241,1.160103,...,-0.109454,-0.272138,0.287057,0.688077,-0.746201,1.637716,-0.210818,-0.765106,0.219520,0.861477
822,2016-04-11 04:00:00,0.171055,-0.015389,0.217936,-0.248803,0.419394,1.009414,-0.258271,-0.042705,-0.818788,...,-0.192783,-0.421701,0.269066,0.035647,-1.724390,0.016291,-0.132865,0.296220,-0.119034,0.107246
823,2016-04-12 04:00:00,0.755738,1.276157,0.541504,-0.142911,1.407753,1.191727,0.310915,3.005065,1.695468,...,0.341807,1.198035,-0.139651,0.306378,0.159054,1.751580,0.270952,0.191017,1.336665,1.044383
824,2016-04-13 04:00:00,0.843279,-0.291221,-0.110381,1.091289,2.375438,3.474108,0.245003,0.151668,0.066625,...,0.761452,0.687738,1.318177,1.566262,1.566036,1.242660,-0.106485,0.469725,2.258318,0.479330
825,2016-04-14 04:00:00,0.002781,0.164807,-0.880520,-0.280167,1.544283,1.036781,-0.192722,0.821349,0.279906,...,-0.050236,0.137521,0.075978,-0.141786,0.264365,-0.187744,-0.106528,0.045989,-0.477801,0.596664
826,2016-04-15 04:00:00,-1.260331,0.173514,-0.225953,-1.062670,-0.631736,-0.092164,0.116073,-0.646089,-0.552787,...,0.276112,0.225575,0.364156,-0.407558,-0.446529,-0.776572,0.565865,-0.449813,-1.028031,-0.467044

In [6]:
period_1 = pd.read_csv('../data/processed/period_1_normalized.csv')
period_1.head(10)

,Unnamed: 0,AAPL,ABBV,AMD,AVGO,BAC,C,CMCSA,COP,CVX,...,MSFT,NFLX,NVDA,ORCL,PFE,SLB,TMUS,UNH,WFC,XOM
0,2016-04-18 04:00:00,-1.497016,0.336809,0.461374,0.092617,0.721274,0.248575,0.569472,1.635022,1.223875,...,0.966358,-1.208216,-0.216491,0.376151,0.278888,1.084075,-0.126180,0.225507,0.917839,0.890720
1,2016-04-19 04:00:00,-0.407128,0.258667,-1.343966,-1.738417,1.210865,0.750686,-0.274274,2.510339,1.481836,...,-0.177980,-5.726771,-0.693612,-0.373618,0.756008,1.916415,0.950142,1.569705,1.598328,0.469153
2,2016-04-20 04:00:00,0.080064,0.276263,0.658858,0.713413,2.067081,1.622520,-1.017790,-0.002000,0.951931,...,-1.129565,0.985700,0.068020,0.038776,0.916103,1.264109,0.440165,1.972641,0.857455,0.640143
3,2016-04-21 04:00:00,-0.775163,0.817645,-0.808014,-0.711548,-0.198289,-0.252054,-0.665763,-1.058563,-0.278137,...,0.161358,-0.815505,-0.104285,-0.242960,-0.005166,-0.645861,0.106924,-0.643390,-0.617263,-0.011516
4,2016-04-22 04:00:00,-0.236854,0.029038,10.182105,-0.411799,0.847038,0.504311,0.157003,1.652605,0.466398,...,-5.514431,0.340728,-0.200264,-0.583778,0.050290,-0.240301,-0.108025,0.619237,0.854526,0.796986
5,2016-04-25 04:00:00,-0.431987,-0.437987,-3.620550,-0.489860,-0.718458,-0.458636,-0.158224,-1.655777,-0.451190,...,0.375836,-1.061876,0.106422,0.115104,-0.199503,-0.936668,1.509756,-0.276684,-0.175778,-0.215566
6,2016-04-26 04:00:00,-0.516419,-0.055060,1.366297,0.545647,0.498109,0.562148,0.023623,2.148361,0.605760,...,-1.031296,-0.549246,-0.037381,-0.282480,-0.478619,0.410088,-3.114335,0.199544,0.607281,0.321500
7,2016-04-27 04:00:00,-4.326026,-0.233748,0.387395,0.224716,-0.370548,0.293729,0.265347,0.009222,1.234828,...,-0.799859,-0.671823,0.717736,0.342126,-0.172648,1.220887,0.564046,-0.920364,0.005234,0.885047
8,2016-04-28 04:00:00,-2.107112,0.451477,-0.871975,-1.317868,-1.074634,-0.855428,-0.218301,-0.546748,-1.220422,...,-1.591884,-0.395344,-1.118258,-1.024167,-0.284973,-0.641770,0.041949,-0.505022,-0.792943,-0.458508
9,2016-04-29 04:00:00,-0.819712,-0.204685,-0.483272,-0.867626,-1.090413,-0.715007,-0.510497,0.116376,-0.218841,...,-0.131346,-0.166220,-0.716889,-0.940186,-0.595480,0.514194,-0.865960,-0.303794,-0.663537,0.393429